### ISSUE TITLE
Uncareted `sanitize.css` dependency causing failure while requiring `postcss-normalize`

### ISSUE THREAD

**Issue by 10hendersonm** [csstools/postcss-normalize#58] opened 2021-09-14 16:11 UTC
[`sanitize.css@13.0.0` removes file `page.css`](https://github.com/csstools/sanitize.css/compare/12.0.0..13.0.0#diff-cf0e02530054350aa3396a6be36d0936e2d8feb37a2f6f6a904616b7afa501d2), which is directly referenced in `cssMap.js`:

https://github.com/csstools/postcss-normalize/blob/5b80f53e46d43d297d7deaec4704c044fa38fb69/src/lib/cssMap.js#L16

As `sanitize.css` is installed at version `*` rather than something like `12.0.0` or `^12.0.0`, `npm` users are auto-upgraded into this breaking `sanitize.css` version. This includes users of [`create-react-app`'s `react-scripts`](https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/package.json#L61).

**Comment by avin** [comment] 2021-09-14 16:22
temp solution for package.json
```
  "scripts": {
     ...
    "preinstall": "npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions"
  }, 
  ...
  "resolutions": {
    "sanitize.css": "12.0.1"
  }
```

**Comment by jonathantneal** [comment] 2021-09-14 16:46
So, @10hendersonm, would an appropriate solution be to protect that code from throwing and releasing that in patch today? Or to force `page.css` back into `sanitize.css`?

I can definitely "coordinate" this.

**Comment by 10hendersonm** [comment] 2021-09-14 17:00
I'll be 100% honest that this isn't my usual space. I dropped a PR (https://github.com/csstools/postcss-normalize/pull/59) but haven't had a chance to check this repo's normal workflows yet to see if I missed any other requirements.

**Comment by 10hendersonm** [comment] 2021-09-14 17:02
Oh, hah, @jonathantneal I didn't realize you have `sanitize.css` as well. You can either code around the removed file, pin this back to the previous `sanitize.css` version, add it back in `sanitize.css`, etc. I'm cool with anything, I just don't have direct access to this level of dependencies as `npm` doesn't have resolutions yet without additional tooling (thanks @avin)

**Comment by DavidHenri008** [comment] 2021-09-14 22:32
I was also having the same problem where the sanitiza.css was somehow not found. The suggested workaround worked for me.

**Comment by rajrajhans** [comment] 2021-09-15 06:54
Can confirm this issue causes `create-react-app` to fail, giving the following error on `start` or `build`:

```
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_module

Loading PostCSS "postcss-normalize" plugin failed: Cannot find module 'sanitize.css/page.css'
Require stack:
- ... \node_modules\react-scripts\node_modules\postcss-normalize\index.cjs
```

**Comment by LQ0611** [comment] 2021-09-15 07:28
I have the same question :'cannot find module ‘sanitize.css/page.css’'

**Comment by rajrajhans** [comment] 2021-09-15 07:32
@LQ0611 for now, a temporary fix would be to pin `sanitize.css`  to `12.0.1`.

Add this in your `package.json`

```
"resolutions": {
   "sanitize.css": "12.0.1"
}
```

**Comment by LQ0611** [comment] 2021-09-15 07:40
Oh, yeah,i do this now. and I hope this question could be completely solved .thank you very much

**Comment by yoyo837** [comment] 2021-09-15 08:57
> @LQ0611 for now, a temporary fix would be to pin `sanitize.css` to `12.0.1`.
> 
> Add this in your `package.json`
> 
> ```
> "resolutions": {
>    "sanitize.css": "12.0.1"
> }
> ```

It only works on `yarn`.

**Comment by yoyo837** [comment] 2021-09-15 09:07
- [ ] 1. https://github.com/csstools/postcss-normalize/pull/59
- [ ] 2. https://github.com/csstools/postcss-normalize/pull/60

Vote this 😄

**Comment by LQ0611** [comment] 2021-09-15 09:08
yeah，' resolutions' is a temporary way, of course , the base way is that the problem is resolved by owner , hahaha

**Comment by LQ0611** [comment] 2021-09-15 09:15
> * [ ]  1. [Pin `sanitize.css` to `12.x` versioning #59](https://github.com/csstools/postcss-normalize/pull/59)
> * [ ]  2. [Removed references to sanitize.css/pages.css #60](https://github.com/csstools/postcss-normalize/pull/60)
> 
> Vote this 😄

I select ‘1’,

**Comment by LQ0611** [comment] 2021-09-15 09:21
> * [ ]  1. [Pin `sanitize.css` to `12.x` versioning #59](https://github.com/csstools/postcss-normalize/pull/59)
> * [ ]  2. [Removed references to sanitize.css/pages.css #60](https://github.com/csstools/postcss-normalize/pull/60)
> 
> Vote this 😄

1，maybe someone useing pages.css?

**Closed as completed** 2021-09-15 10:59 UTC

**Comment by 10hendersonm** [comment] 2021-09-15 12:48
Without updating the `sanitize.css` dependency semver range, does this in essence prevent `sanitize.css` from ever being allowed to breaking change again?

**Comment by bmuenzenmeyer** [comment] 2021-09-15 14:44
the right thing to do is revisit https://github.com/csstools/postcss-normalize/blob/HEAD/CHANGELOG.md#900-april-12-2020 which introduced the `*` dependency concept. we have goodwill semver releases like https://github.com/csstools/sanitize.css/releases/tag/v13.0.0 that  unintentionally broke downstream

**Comment by jonathantneal** [comment] 2021-09-15 16:05
@bmuenzenmeyer, aye. For now, I’m _side-stepping_ the issue by using `path.join` rather than `resolve` to prevent throws.
